config/routes.rb
Rails.application.routes.draw do
  root 'overview#about_me'

  get 'overview/hobbies'
  get 'overview/projects'
  get 'overview/science'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/overview_controller.rb
class OverviewController < ApplicationController
  # All pages are static so putting all actions in one controller

  def about_me
    @active_page = NAV_OPTIONS[:about_me]
    @about_me = AboutMePresenter.new
  end

  def hobbies
    @active_page = NAV_OPTIONS[:hobbies]
  end

  def projects
    @active_page = NAV_OPTIONS[:projects]
  end

  def science
    @active_page = NAV_OPTIONS[:science]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title= 'Dan Stucky'
    = csrf_meta_tags
    = csp_meta_tag

    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

  %body
    .flex-wrapper.webapp
      = render template: 'layouts/side_nav_bar'
      = render template: 'layouts/page_content'

app/views/layouts/page_content.html.haml
#content
  %nav.navbar.navbar-expand-lg.navbar-light.bg-light
    %button.btn.btn-info#sidebarCollapse{type: 'button'}
      = fa_icon 'angle-double-left', class: 'hide-sidebar-icon'
      %span.hide-sidebar-text= 'Hide Sidebar'
  = yield

app/views/layouts/side_nav_bar.html.haml
%nav#sidebar
  .sidebar-header
    %h3= 'Dan Stucky'
    %h6= 'Software Engineer'

  %ul.list-unstyled.components
    = link_to root_path do
      %li{class: ('active' if @active_page == NAV_OPTIONS[:about_me])}= 'Who I Am'
    %li= 'Resume'
    = link_to overview_projects_path do
      %li{class: ('active' if @active_page == NAV_OPTIONS[:projects])}= 'Personal Projects'
    = link_to overview_science_path do
      %li{class: ('active' if @active_page == NAV_OPTIONS[:science])}= 'Biology Research'
    = link_to overview_hobbies_path do
      %li{class: ('active' if @active_page == NAV_OPTIONS[:hobbies])}= 'Hobbies'

app/views/overview/about_me.html.haml
.about-me-page
  .flex-wrapper
    .column.column-2
      .about-me-card.card
        %h4.card-header= 'About Me'
        .card-body
          = image_tag("dan_science.png")
          %p= @about_me.description_text

      .contact-info-card.card
        %h4.card-header= 'Contact'
        .card-body
          %p= fa_icon 'map-marker', text: 'Kansas City, MO'
          %p= fa_icon 'envelope', text: 'danfstucky@gmail.com'

      .education-card.card
        %h4.card-header= 'Education'
        .card-body
          %ul.list-unstyled
            %li= fa_icon 'graduation-cap', text: 'B.S. Computer Science'
            %li.text-secondary= 'University of Missouri Kansas City (2016)'
          %ul.list-unstyled
            %li= fa_icon 'graduation-cap', text: 'M.S. Molecular Genetics'
            %li.text-secondary= 'Kansas State University (2013)'
          %ul.list-unstyled
            %li= fa_icon 'graduation-cap', text: 'B.S. Biology'
            %li.text-secondary= 'Truman State University (2011)'

    .column.column-2
      .skills-card.card
        %h4.card-header= 'Skills'
        .card-body
          %p= '<Create a d3.js chart for this in the future.>'
          - @about_me.skills.each do |skill|
            %p= "#{skill[:text]} - #{skill[:score]}"

      .github-card.card
        %h4.card-header= 'My GitHub'
        .card-body
          = link_to 'https://github.com/danfstucky'

app/views/overview/hobbies.html.haml
.hobbies-page
  %table.interests-header
    %tr.select-image-row
      %td.active= image_tag("hiking.png", size: "125")
      %td.inactive= image_tag("code.png", size: "125")
      %td.inactive= image_tag("chromosome.png", size: "125")
      %td.inactive= image_tag("halo.png", size: "125")
      %td.inactive= image_tag("muse.png", size: "125")
      %td.inactive= image_tag("trigun.png", size: "125")
    %tr.select-icon-row
      %td= fa_icon 'angle-down', class: 'fa-5x active selection-1'
      %td= fa_icon 'angle-down', class: 'fa-5x d-none selection-2'
      %td= fa_icon 'angle-down', class: 'fa-5x d-none selection-3'
      %td= fa_icon 'angle-down', class: 'fa-5x d-none selection-4'
      %td= fa_icon 'angle-down', class: 'fa-5x d-none selection-5'
      %td= fa_icon 'angle-down', class: 'fa-5x d-none selection-6'

  .interests-panel
    .selection-1.active
      %h3.bg-light= 'Hiking'
      %p= 'My girlfriend and I love going on hikes together and. Our favorite destinations are wooded mountain areas such as Colorado and the Pacific Northwest.'
      
    .selection-2.d-none
      %h3.bg-light= 'Programming'
      .flex-wrapper
        .column.column-3
          %p= "I got off to a later start than most when it comes to my programming career due to my studies in genetics, but I have not looked back since making the switch. I devote a good chunk of my free time to working on personal coding projects of my choosing. These range from fun games I play and share with others, to more practical uses that aid me in some purpose. A list of my more recent endeavors can be found on the Personal Projects page of this site.\nI prefer working with higher-level languages when able since progress is often much quicker. I am always looking to learn new technologies and expand my knowledge!"
        .column
          %h5= 'Favorite Languages'
          = image_tag("tech_icons/ruby-icon.png")
          = image_tag("tech_icons/python-icon.png")
          = image_tag("tech_icons/js-icon.png")

    .selection-3.d-none
      %h3.bg-light= 'Science'

    .selection-4.d-none
      %h3.bg-light= 'Gaming'
      %h5= 'Favorite Games'
      %table.games-list
        %tr
          %td= image_tag("loz.png")
        %tr
          %td= image_tag("smite.png")
        %tr
          %td= image_tag("halo2.png")
        %tr
          %td= image_tag("mario_kart.png")
        %tr
          %td= image_tag("pokemon.png")
        %tr
          %td= image_tag("wow.png")

    .selection-5.d-none
      %h3.bg-light= 'Music'

    .selection-6.d-none
      %h3.bg-light= 'Anime'

app/views/overview/projects.html.haml
- # Refactor this view
.projects-page
  .card
    %h4.card-header= 'Pokemon Fan Game'
    .card-body
      .flex-wrapper
        .column.column-2
          .pokelogo
            = image_tag('PokemonPics/test.png')
            %p= 'Pokemon fan game created inside RPG Maker using Ruby scripts to program game mechanics and environment/character interaction. This is still a work in progress and will never be used for profit as it borrows many assets from the Nintendo franchise. I have always enjoyed playing the Pokemon games and have had a blast creating and play-testing this game with my own ideas.'

        .column.column-2
          #poke-carousel.carousel.slide{data: {ride: 'carousel'}}
            %ol.carousel-indicators
              %li.active{data: {target: '#poke-carousel', 'slide-to': 0}}
              %li{data: {target: '#poke-carousel', 'slide-to': 1}}
              %li{data: {target: '#poke-carousel', 'slide-to': 2}}
              %li{data: {target: '#poke-carousel', 'slide-to': 3}}
              %li{data: {target: '#poke-carousel', 'slide-to': 4}}
              %li{data: {target: '#poke-carousel', 'slide-to': 5}}
              %li{data: {target: '#poke-carousel', 'slide-to': 6}}
              %li{data: {target: '#poke-carousel', 'slide-to': 7}}

            .carousel-inner
              .carousel-item.active
                = image_tag('PokemonPics/screenshot1.png')

              .carousel-item
                = image_tag('PokemonPics/screenshot2.png')

              .carousel-item
                = image_tag('PokemonPics/screenshot3.png')

              .carousel-item
                = image_tag('PokemonPics/screenshot4.png')

              .carousel-item
                = image_tag('PokemonPics/screenshot5.png')

              .carousel-item
                = image_tag('PokemonPics/screenshot6.png')

              .carousel-item
                = image_tag('PokemonPics/screenshot7.png')

              .carousel-item
                = image_tag('PokemonPics/screenshot8.png')

            .carousel-control-prev
              = link_to '#poke-carousel', role: 'button', data: {slide: 'prev'} do
                %span.carousel-control-prev-icon{'aria-hidden': true}
                %span.sr-only= 'Previous'

            .carousel-control-next
              = link_to '#poke-carousel', role: 'button', data: {slide: 'next'} do
                %span.carousel-control-next-icon{'aria-hidden': true}
                %span.sr-only= 'Next'

  .card
    %h4.card-header= 'Tactical Arbitrage Command Line App'
    .card-body
      %p= 'A Node.js command line application for finding great opportunities to buy and sell items from Walmart and Amazon at a profit. It pulls down information for millions of items from both sites and outputs a list of the top picks based on profit margin, buyer reviews, and consumer demand.'
      = link_to 'Project Github Link', 'https://github.com/sulaimonlasisi/clearance-app', target: :_blank

  .card
    %h4.card-header= 'Smite Spec'
    .card-body
      %table.smite-spec-images
        %tr
          %td= image_tag('smite_spec/screenshot1.png')
          %td= image_tag('smite_spec/screenshot2.png')
          %td= image_tag('smite_spec/screenshot3.png')
      %p= "Smite Spec is intended for all players of the popular multiplayer online battle arena game, Smite. It allows users to find player and clan statistics to help improve their play style and team performance in matches or simply have fun viewing your friends' data. Unlike other third party Smite apps such as SmiteRepo, Smite Spec focuses on the player. The user can easily track personal statistics for their favorite and best god characters to play as, and compare their stats to in-game friends. It is only available for Android."
      = link_to 'Project Github Link', 'https://github.com/danfstucky/SmiteSpec', target: :_blank